dist: trusty
sudo: false

language: generic
branches:
  only:
    - master

env:
  global:
    - NEOMAKE_DOCKER_IMAGE: neomake/vims-for-tests:8@sha256:09c09ceccc507ce2170287872d582803fefb6cb57b95a6a6bdd81bc6b9afc495

matrix:
  fast_finish: true
  include:
    - env: ENV=travis_test
      services:
        - docker
    - env: ENV="travis_lint check"
      language: python
    - env: ENV=testnvim
    - env: ENV=testvim

install:
  - |
    set -e
    if [ "$ENV" = "travis_test" ]; then
      echo "Looking for changed files in $TRAVIS_COMMIT_RANGE."
      if ! git diff --exit-code --quiet "$TRAVIS_COMMIT_RANGE" doc/neomake.txt; then
        MAKE_ARGS="$MAKE_ARGS docker_vimhelplint"
        echo 'doc/neomake.txt changed, running docker_vimhelplint'
      fi
    fi
    if [ "$TEST_VIM" = "nvim" ]; then
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
      # Install vim-vimhelplint for one build.
      make build/vimhelplint
    fi
    if [[ "$ENV" = "testvim" ]]; then
      vim --version
      if ! vim --version 2>&1 | grep -F 'VIM - Vi IMproved 7.4' -A1 | grep -q '^Included patches: 1-52'; then
        echo 'Unexpected Vim version (expected 7.4.52)' >&2
        exit 1
      fi
    fi
    umask 022

script:
  - make --keep-going $ENV $MAKE_ARGS || exit 1
