dist: trusty
sudo: false
group: edge

language: none
branches:
  only:
    - master

env:
  global:
    - NEOMAKE_DOCKER_IMAGE: neomake/vims-for-tests:5@sha256:58d233a76e29436f10a5b0f9642ceb7f6a361f65f49dfedf0a821ef182568e8b

jobs:
  fast_finish: true
  include:
    - stage: Basic tests
      env: ENV=testnvim
    - env: ENV=testvim
    - env: ENV=vint
      language: python

    # - stage: test
    - env: ENV=vimlint
    - env: ENV=docker_test MAKE_ARGS=DOCKER_VIM=neovim-v0.2.0
      services:
        - docker
    - env: ENV=docker_test MAKE_ARGS=DOCKER_VIM=neovim-v0.1.7
      services:
        - docker
    - env: ENV=docker_test MAKE_ARGS=DOCKER_VIM=vim-master
      services:
        - docker
    - env: ENV=docker_test MAKE_ARGS=DOCKER_VIM=vim8069
      services:
        - docker
    # Vim 7.3.429 (Ubuntu Precise)
    - env: ENV=docker_test MAKE_ARGS=DOCKER_VIM=vim73
      services:
        - docker
    - env: ENV=check
      services:
        - docker

script: true
