version: 2

common: &common
  filters:
    branches:
      only:
        - circleci
  working_directory: ~/repo
  steps:
    - checkout
    # - run:
    #     name: Install Neovim
    #     command: eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
    - run:
        name: Run make {{ .Environment.MAKE_ARGS }}
        command: |
          make --keep-going $MAKE_ARGS
    - run:
        name: upload coverage results for non-checkqa builds
        command: |
          if [[ "$CIRCLE_JOB" != 'check' ]]; then
            set -x
            src_dir="$PWD"
            shopt -s nullglob

            profiles="$(find build/coverage -name '*.profile')"
            if [[ -z "$profiles" ]]; then
              echo "warning: no profiles found in $d."
              exit 2
            fi
            sed -i "s:^SCRIPT  /testplugin/:SCRIPT  $src_dir/:" $profiles

            covimerage write_coverage --source . $profiles
            covimerage report -m
            covimerage xml --include 'autoload/*' --include 'plugin/*' --include 'tests/*'
            codecov -X search gcov pycov -f coverage.xml --required \
              --name "$prof_name" --flags ${CIRCLE_JOB%%-*} ${CIRCLE_JOB//-/}
            set +x
          fi
jobs:
  nvim-master:
    <<: *common
    docker:
      - image: neomake/vims-for-tests:circleci
        environment:
          MAKE_ARGS=testcoverage
          TEST_VIM=/vim-build/bin/neovim-master
  nvim-017:
    <<: *common
    docker:
      - image: neomake/vims-for-tests:circleci
        environment:
          MAKE_ARGS=testcoverage
          TEST_VIM=/vim-build/bin/neovim-v0.1.7
  nvim-020:
    <<: *common
    docker:
      - image: neomake/vims-for-tests:circleci
        environment:
          MAKE_ARGS=testcoverage
          TEST_VIM=/vim-build/bin/neovim-v0.2.0
  vim-master:
    <<: *common
    docker:
      - image: neomake/vims-for-tests:circleci
        environment:
          MAKE_ARGS=testcoverage
          TEST_VIM=/vim-build/bin/vim-master
  vim-8069:
    <<: *common
    docker:
      - image: neomake/vims-for-tests:circleci
        environment:
          MAKE_ARGS=testcoverage
          TEST_VIM=/vim-build/bin/vim8069
  vim-74-xenial:
    <<: *common
    docker:
      - image: neomake/vims-for-tests:circleci
        environment:
          MAKE_ARGS=testcoverage
          TEST_VIM=/vim-build/bin/vim74-xenial
  vim-74-trusty:
    <<: *common
    docker:
      - image: neomake/vims-for-tests:circleci
        environment:
          MAKE_ARGS=testcoverage
          TEST_VIM=/vim-build/bin/vim74-trusty
  vim-73:
    <<: *common
    docker:
      - image: neomake/vims-for-tests:circleci
        environment:
          MAKE_ARGS=testcoverage
          TEST_VIM=/vim-build/bin/vim73

  check:
    <<: *common
    docker:
      - image: neomake/vims-for-tests:circleci
        environment:
          MAKE_ARGS=check check_docker

workflows:
  version: 2
  test:
    jobs:
      # - nvim-master
      # - nvim-017
      # - nvim-020
      # - vim-master
      # - vim-8069
      # - vim-74-xenial
      # - vim-74-trusty
      # - vim-73
      - check
