version: 2

common: &common
  docker:
    - image: neomake/vims-for-tests:41@sha256:3aa6bb57ba3fb05c361ae19b1c365aeec34bf3e62b16a721d16bc67484e299a4
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: Run tests
        command: |
          cc-test-reporter before-build
          make --keep-going testcoverage TEST_VIM=$TEST_VIM
    - run:
        name: Handle coverage
        command: |
          set -x
          mkdir test-results
          cp -a .coverage_covimerage test-results/.coverage_covimerage.$CIRCLE_BUILD_NUM

          # Upload to codecov, which handles this per job itself.
          coverage xml
          # -Z: exit with 1 in case of failures.
          codecov -Z -X search -X gcov -X pycov -f coverage.xml \
            -n "$CIRCLE_JOB" -F "${CIRCLE_JOB%%-*}" -e CIRCLE_JOB
          set +x
    - persist_to_workspace:
        root: .
        paths:
          - test-results/

jobs:
  nvim-031:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-v0.3.1
  nvim-017:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-v0.1.7
  nvim-master:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/neovim-master
  vim-81:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim81
  vim-80:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim80
  vim-74-xenial:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim74-xenial
  vim-74-trusty:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim74-trusty
  vim-73:
    <<: *common
    environment:
      TEST_VIM=/vim-build/bin/vim73

  checkqa:
    <<: *common
    steps:
      - checkout
      - run:
          name: Checks
          command: |
            set -x
            python -m ensurepip --user
            PATH=$HOME/.local/bin:$PATH
            pip3 install --user git+https://github.com/Kuniwak/vint.git@master
            vint --version
            make --keep-going check check_docker check_lint_diff vint
            set +x

workflows:
  version: 2
  test:
    jobs:
      - checkqa
