version: 2

common: &common
  filters:
    branches:
      only:
        - circleci
  working_directory: ~/repo
  steps:
    - checkout
    # - run:
    #     name: Install Neovim
    #     command: eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
    - run:
        name: Run make {{ .Environment.MAKE_ARGS }}
        command: |
          make --keep-going $MAKE_ARGS || exit 1
    - run:
        name: upload coverage results for non-checkqa builds
        command: |
          if [[ "$CIRCLE_JOB" != 'check' ]]; then
            set -x
            src_dir="$PWD"
            shopt -s nullglob
            for d in profile-output.*; do
              prof_name=${d#profile-output.}
              prof_flags=${prof_name//-/ }
              prof_flags=${prof_flags//./}

              profiles="$(find "$d" -name '*.profile')"
              if [[ -z "$profiles" ]]; then
                echo "warning: no profiles found in $d."
                exit 2
              fi
              sed -i "s:^SCRIPT  /testplugin/:SCRIPT  $src_dir/:" $profiles

              covimerage write_coverage --source . $profiles
              covimerage report -m
              covimerage xml --include 'autoload/*' --include 'plugin/*' --include 'tests/*'
              codecov -X search gcov pycov -f coverage.xml --required \
                --name "$prof_name" --flags $CODECOV_FLAGS $prof_flags
            done
            set +x
          fi
jobs:
  nvim:
    <<: *common
    docker:
      - image: neomake/vims-for-tests:circleci
        environment:
          MAKE_ARGS=testcoverage
          NEOMAKE_TEST_PROFILE_DIR=profile-output.nvim-nvimmaster
          TEST_VIM=/vim-build/bin/neovim-master
  vim73:
    <<: *common
    docker:
      - image: neomake/vims-for-tests:circleci
        environment:
          MAKE_ARGS=testcoverage
          TEST_VIM=/vim-build/bin/vim73
          NEOMAKE_TEST_PROFILE_DIR=profile-output.vim73
  check:
    <<: *common
    docker:
      - image: neomake/vims-for-tests:circleci
        environment:
          MAKE_ARGS=check

workflows:
  version: 2
  test:
    jobs:
      - nvim
      - vim73
      # - check
